line-length = 100
target-version = "py311"

[lint]
select = ["ALL"]

ignore = [
  "T",  # flake8-print
  "S",  # flake8-bandit
  "PLR2004",  # Magic value comparisons
  "N813",  # Import "as" casing
  "INP001",  # bazel python doesn't have __init__.py
  # Recommended to avoid conflicting with formatter
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191",
  "E111",
  "E114",
  "E117",
  "D203",
  "D206",
  "D213",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
]
